"""Removed the default value from the branch attribute

Revision ID: 479cce011657
Revises: f34d8db38e58
Create Date: 2024-10-10 17:22:41.625555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479cce011657'
down_revision = 'f34d8db38e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'branch',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'branch',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
