"""Modified the session saver model

Revision ID: 8ca8376bf701
Revises: e46f5bf93142
Create Date: 2024-09-19 20:15:36.359408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ca8376bf701'
down_revision = 'e46f5bf93142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_saver', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.add_column('session_saver', sa.Column('role', sa.LargeBinary(), nullable=True))
    op.add_column('session_saver', sa.Column('department', sa.String(), nullable=True))
    op.add_column('session_saver', sa.Column('country', sa.String(), nullable=True))
    op.drop_constraint('session_saver_session_id_key', 'session_saver', type_='unique')
    op.create_unique_constraint(None, 'session_saver', ['employee_id'])
    op.drop_column('session_saver', 'data')
    op.drop_column('session_saver', 'session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_saver', sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('session_saver', sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'session_saver', type_='unique')
    op.create_unique_constraint('session_saver_session_id_key', 'session_saver', ['session_id'])
    op.drop_column('session_saver', 'country')
    op.drop_column('session_saver', 'department')
    op.drop_column('session_saver', 'role')
    op.drop_column('session_saver', 'employee_id')
    # ### end Alembic commands ###
