"""Added a profile picture column to the employee model

Revision ID: cfab984c0259
Revises: 4667d59fa95e
Create Date: 2024-08-22 19:56:04.938958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfab984c0259'
down_revision = '4667d59fa95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('profile_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'profile_picture')
    # ### end Alembic commands ###
