"""Added the branch in the employee model

Revision ID: f34d8db38e58
Revises: 889fb503b87a
Create Date: 2024-10-10 15:55:41.780464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34d8db38e58'
down_revision = '889fb503b87a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('branch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'branch')
    # ### end Alembic commands ###
