name: Run Python script on January 1st

on:
  schedule:
    # Runs at midnight UTC on the 1st of January every year
    - cron: '* * * * *'

jobs:
  run-python-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # Specify your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt # if you have a requirements.txt

      - name: Run Python script
        run: |
          python Cron/Update.py
          
