# This workflow will run a Python script located in the Cron folder
name: Leave Days Update Cron Job

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: read

jobs:
  run-python-file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python script
      run: |
        python Cron/Update.py